# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

 Email: 'appmoviestore@gmail.com'
 Password: '16july1994'
 Facebook_app_key: '152823678696693'
 Facebook_app_secret: '10ee39caedc7881e3626117d2aa6c179'
 Google_app_key: '309656434560-48kuqv49ls58qpiitjum35bi929ge4es.apps.googleusercontent.com'
 Google_app_secret: 'UrdE_sUKDkDoYsPAmIy1drS-'
 Twitter_app_key: '7E7QEVI9ZOe6jDXc4dwMOgqIv'
 Twitter_app_secret: 'Wu5pUsfLMEuDbsgxXS1M4tkU27NGLxHYmOKcYMha6IhDjigP6X'
